### ISSUE TITLE
delete my account

### ISSUE THREAD

**Issue by katjaq** [hackmdio/codimd#1008]
Hello
great tool! It looks awesome and I would love to get started using it. However, hahaaa, how can I delete my account and setup new? I cannot seem to find this option. 

Many thanks
sunny regards from Paris
katja

**Comment by katjaq** [comment]
Sorry, I just saw a related issue and will close this one here

**Comment by SISheogorath** [comment]
Also see the user area on the main page:

![image](https://user-images.githubusercontent.com/8719867/46808691-2de65800-cd6d-11e8-8666-c024edfabbdd.png)

**Comment by katjaq** [comment]
Thank you very much for your reply :)
hmmm, I only see "Features" and "Sign out" – but non of the rest OO

**Comment by SISheogorath** [comment]
Seems like the version is not up to date. Check the "Releases"-link to see what their latest version is.

[The deletion feature was introduced in 1.2.0](https://demo.codimd.org/s/release-notes#Enhancements1).

We highly recommend to upgrade to the latest release since we don't maintain older ones :)
