### ISSUE TITLE
support lutim for image hosting

### ISSUE THREAD

**Issue by oupala** [hackmdio/codimd#1109]
It would be great if codimd can support [lutim](https://framagit.org/fiat-tux/hat-softwares/lutim) in addition to imgur for hosting dynamically uploaded image.

It is a way to rely on free software only.

**Comment by SISheogorath** [comment]
Sounds like a nice alternative to imgur. If you are interested in implementing it, have a look at https://github.com/hackmdio/codimd/tree/master/lib/web/imageRouter

It's build to be extendible so we would welcome a lutim.js in there :)

Since I couldn't find any npm package for it, I guess you have to do some pioneer work here. I guess using the `request` library could be enough.

**Comment by ccoenen** [comment]
another possibility is local file storage. You can set this up with the `imageUploadType` set to `filesystem`.

**Comment by ccoenen** [comment]
I marked these accodingly, If anyone feels the scope is too massive for a "first issue", let me know and I'll remove that tag.

**Comment by oupala** [comment]
In fact, this issue depends mainly on the availability of a js library for using the lutim api.

The developer of lutim does not like javascript, and hence wont develop such library.

If anyone is willing to do that, just check this issue: [a js lib for interacting with lutim](https://framagit.org/fiat-tux/hat-softwares/lutim/issues/96).

Once this lib is available on [npmjs](http://npmjs.org), this issue is a good "first issue". Meanwhile, it looks like more a issue "not for beginners". More opinions needed though.

**Comment by SISheogorath** [comment]
Actually one could use the request library, since we only need a minimal set of the API: https://framagit.org/fiat-tux/hat-softwares/lutim/wikis/API#add-images

When someone provides the same functionality as the curl statement in the mentioned wiki entry, there is no problem with pushing images onto it. And that's definitely doable, even for a beginner.

**Comment by oupala** [comment]
Ok, you might be right. Let's keep the "good first issue" tag.

**Comment by SISheogorath** [comment]
Should basically look like this:

```js
var request = require('request');

var formData = {
 format: 'json',
  // can be removed with the file stream if wanted
  file: fs.createReadStream(uploadedFile),
  }
};

request.post({url:'https://lut.im', formData: formData});

```

Some minor changes are may needed to add some options but in general, that's it.
