### ISSUE TITLE
codimd (especially its docker image) should create its database does not exist

### ISSUE THREAD

**Issue by Trolldemorted** [hackmdio/codimd#1115]
The codimd docker-compose documentation states that you can use a [postgres backend](https://github.com/hackmdio/codimd-container/blob/master/docker-compose.yml#L16):

```yml
    environment:
      # DB_URL is formatted like: <databasetype>://<username>:<password>@<hostname>/<database>
      # Other examples are:
      # - mysql://hackmd:hackmdpass@database:3306/hackmd
      # - sqlite:///data/sqlite.db (NOT RECOMMENDED)
      # - For details see the official sequelize docs: http://docs.sequelizejs.com/en/v3/
      - CMD_DB_URL=postgres://hackmd:hackmdpass@database:5432/hackmd
```

Unfortunately codimd crashes if the database does not exist:
```
codimd_1    | Unhandled rejection SequelizeConnectionError: database "hackmd" does not exist
codimd_1    |     at /codimd/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:110:20
codimd_1    |     at Client.<anonymous> (/codimd/node_modules/pg/lib/client.js:203:5)
codimd_1    |     at emitOne (events.js:116:13)
codimd_1    |     at Connection.emit (events.js:211:7)
codimd_1    |     at Socket.<anonymous> (/codimd/node_modules/pg/lib/connection.js:133:12)
codimd_1    |     at emitOne (events.js:116:13)
codimd_1    |     at Socket.emit (events.js:211:7)
codimd_1    |     at addChunk (_stream_readable.js:263:12)
codimd_1    |     at readableAddChunk (_stream_readable.js:250:11)
codimd_1    |     at Socket.Readable.push (_stream_readable.js:208:10)
codimd_1    |     at TCP.onread (net.js:601:20)
```

Your official docker-compose.yml circumvents this by specifying a default database to postgres, but postgres allows only [one default database to be specified in POSTGRES_DB](https://hub.docker.com/_/postgres):
>This optional environment variable can be used to define a different name for the default database that is created when the image is first started. If it is not specified, then the value of POSTGRES_USER will be used.

so you cannot use codimd's image in a docker-compose.yml with other services which use the same postgres. Could you create the database if it does not exist?

**Comment by SISheogorath** [comment]
This is pretty much intended. Creating a database should always be a manual step and the application shouldn't have the rights to do that. It's also recommended to **not use** the database backend for different services. At least in a [microservice architecture](https://microservices.io/patterns/data/database-per-service.html), which we try to provide, it's not recommended to mix them.

Of course you refer to running instances of a DB software. I still advice against putting multiple databases together if you are not around with a DBA and running a HA DB cluster. Otherwise, you don't get any benefits out of it. Running more Postgres instances is cheap. Our demo instances uses less than 50MB of RAM and almost no CPU. So I highly recommend to just run a second Postgres container for your other service.

Feel free to reach out either here or for a more interactive discussion in our [Matrix channel](https://riot.im/app/#/room/#codimd:matrix.org)

**Comment by Trolldemorted** [comment]
If you like the microservice architecture that much I will give codi its own database.

However your docker-compose.yml does not remove the rights to create more databases from the application, you might want to adjust that.
