### ISSUE TITLE
Far too much Sessions after One week of running HackMD

### ISSUE THREAD

**Issue by Avalarion** [hackmdio/codimd#1215]
Hey ho together,

we ( the TYPO3 Project ) are planning to move from etherpad to CodiMD. Our first tests were 8 month ago and it worked like a charm, thank you for your work!

One problem on our side was, that after one week of running we've hat ~200.000 Sessions after running HackMD ( I know, this is not CodiMD ) for one week.
Is there a possibility to move this sessions to a non persistent redis db or is there an (automatically) cleanup already in CodiMD?

Have a nice week together,

Bastian

**Comment by jackycute** [comment]
Hi @Avalarion,
Thanks for reporting!

Since we use express-session, it should delete expired session automatically.
I think you could set `sessionLife` shorter (default is 14 days) and that might reduce inactive sessions.
Currently we don't use redis or any other KV store, so moving session storage to there might take some time to develop.

**Comment by Avalarion** [comment]
Thank you for this information. I guess I need to dig some code to check if Redis would work, but if the default session time is 14 days we are going to do a new check with 14 days of life time and see if this stays stable or we have a problem there.

As this is no real bug and we have no possibility to really report back right now if this is solved, I am closing this ticket now and will reporten it, if we see problems in the future!

Thanks for your help!
