### ISSUE TITLE
Feature Request: Holding a key (hjkl) in VIM edit mode continues to scroll up

### ISSUE THREAD

**Issue by aThorp96** [hackmdio/codimd#1237]
This is something I feel is pretty crucial to using the editor in VIM mode.

**Comment by Yukaii** [comment]
Assuming you're using macOS, please follow the tutorial to enable "key repeating":

https://www.idownloadblog.com/2015/01/14/how-to-enable-key-repeats-on-your-mac/

If not, please providing more information about 

- Your operation system
- Browser version
- Running CodiMD version

So that we can help you 👍
