### ISSUE TITLE
Question: Why do two different URLs of different lengths exist to identify a note?

### ISSUE THREAD

**Issue by Rob3681** [hackmdio/codimd#1388]
Why do two different URLs of different lengths exist to identify a note?

For example:

(1) https://demo.codimd.org/rjAdha4SSGOPbGyhTKbmcA

and

(2) https://demo.codimd.org/s/rJx965qe8

If the permission is set to "Freely", everyone can call https://demo.codimd.org/s/rJx965qe8/edit to get to (1). If you restrict access so that guests cannot edit the note, it does not matter whether they know link (1) or (2) - you cannot edit the note as a guest. There is therefore no reason for these two URLs, neither for security reasons nor to limit the authorization.

If I want to make a note editable and readable for everyone who owns the URL, it is better to have an ID that is as long as possible, which cannot be easily guessed. 9 characters (<64 bits entropy) seem very small to me.

**Comment by jackycute** [comment]
Hi @Rob3681,

Thanks for reporting.

So let's say there are two types of note id:
1. long id, like: 1oLWCDC9T66-ldEAd7djaA
2. short id, like: 8cwdFg9no

The long id was intended to be used for edit page like: https://codimd-app.herokuapp.com/1oLWCDC9T66-ldEAd7djaA
And the short was intended to be used for publishing like: https://codimd-app.herokuapp.com/s/8cwdFg9no

But since the published page doesn't know the long id, when people click the edit button on the top right of the published page, it needs a route for returning back to edit page, and that is like: https://codimd-app.herokuapp.com/s/8cwdFg9no/edit

It doesn't really matter if people can guess the long id or short id, you should always set the [permission](https://codimd-app.herokuapp.com/s/features#Permissions) right, or people can also use short id to hit your edit page like: https://codimd-app.herokuapp.com/8cwdFg9no (this also do the redirection).

And last, we don't maintain https://demo.codimd.org, please use https://codimd-app.herokuapp.com as example.

**Comment by jackycute** [comment]
Feel free to reopen if you still confuse about this.
