### ISSUE TITLE
default text not loaded when using direct URL note creation

### ISSUE THREAD

**Issue by fmichonneau** [hackmdio/codimd#1414]
If there is content in the `./public/default.md` file, creating a new note by clicking on the "New" button in the navigation bar correctly creates a new note pre-filled with the content of the default file. However, when creating a new note by directly accessing a URL (using `CMD_ALLOW_FREEURL=true`), the note is blank and doesn't contain the default content.

**Comment by jackycute** [comment]
Hi @fmichonneau,
Thanks for reporting to us.

I traced out code and found that the free url actually find the corresponding docs file in the public path (like `/test` will find `/public/docs/test.md`) and tries to put the content from the file.
Since the file doesn't exist in this case, it didn't catch it but ignore to get the content from default md. I think this might be a bug.
See code here:
https://github.com/hackmdio/codimd/blob/develop/lib/models/note.js#L100

**Comment by jackycute** [comment]
Fixed by https://github.com/hackmdio/codimd/pull/1674
