### ISSUE TITLE
Editor toolbar and statusbar inconsistent position

### ISSUE THREAD

**Issue by tamo** [hackmdio/codimd#1592]
public/js/index.js has a number of lines related to scrollbarStyle
for putting toolbar and statusbar in a relative position
when visibleXS (very narrow windows or portlait phones).

But it doesn't setOption() when needed.
The only occurrence is at $(document).ready().

So, imagine this case:
1. Open CodiMD in a wide (non-XS) window: scrollbarStyle is 'overlay'
2. Resize it to make it narrow enough to be XS: scrollbarStyle remains 'overlay'

And vice versa:
1. Open CodiMD in a narrow (XS) window: scrollbarStyle is 'native'
2. Widen it to non-XS: scrollbarStyle remains 'native'

You can be more careful about scrollbarStyle when resizing the window or changing the mode.

(Personally I don't like native style at all even with smartphones.
I'd suggest you delete all 'native' scrollbarStyle code and stick to 'overlay'.)

**Comment by jackycute** [comment]
Hi @tamo, thanks for suggestion.
We did this intentionally because the native scroll bar can detect the page body scrolling thus hide the nav bar of the browser on mobile. This can make the screen read experience lots better.
The way we detect mobile is by the screen width, so if you load the note and the window width is XS it will load the scrollbar as native. I don't see there will be many user want to switch between wide screen and XS screen while writing.

**Comment by tamo** [comment]
> I don't see there will be many user want to switch between wide screen and XS screen while writing.

I do, but I'm okay with it.
