### ISSUE TITLE
History page display is misaligned

### ISSUE THREAD

**Issue by u1ymd** [hackmdio/codimd#1778]
After updating to v2.4.2, the history page is misaligned.
This makes it impossible to press some buttons.
This is occurring in Chrome and Safari.

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/13217597/194466829-1d965a30-c3d0-4aa4-ac20-9edbceaef4e9.png">

**Comment by slhck** [comment]
Same here, this actuall makes it impossible to use the app at all! 

Adding this to the CSS provides a temporary fix:

```css
#history .form-inline {
    margin-top: 20px;
}
```

**Comment by u1ymd** [comment]
"New note" button area still looks a little low, but the button can now be pressed. 
Thanks for your help.

<img width="868" alt="image" src="https://user-images.githubusercontent.com/13217597/196844245-c47ed53d-e2cc-4781-ab36-6cb97c874a97.png">

**Comment by slhck** [comment]
Please leave this issue open. It's still a bug that needs to be fixed!

**Comment by jackycute** [comment]
PR is welcomed!

same as #1783

**Comment by slhck** [comment]
I've looked at the code a while ago and I couldn't find the part that is relevant for that. Otherwise I would've proposed a fix.

You have an open bug that affects the entire UI in a big way, initially said you were looking at it, then you are asking for PRs to fix it. I find this a bit strange.

While no open source maintainer is forced to provide support for their software, you are in the best position to fix this within probably minutes. So I hope this can be addressed soon.

**Comment by jackycute** [comment]
@slhck sorry for the confusion, I getting back this just now and found the issue is pretty small as you mentioned. So I think it would be a good opportunity for the issue opener to open PR and earn some credits.
I would love to fix this if no one responses.

**Comment by slhck** [comment]
Thanks. As I said, I checked the code but I couldn't find the relevant part to propose the fix.   I'm fact the most recent release broke this, and I couldn't find the breaking commit (I checked all the diffs)...

**Comment by jackycute** [comment]
Maybe that's the browser version updates broke this, I will propose a fix.
