### ISSUE TITLE
table of contents tag only displays 3 levels of headline

### ISSUE THREAD

**Issue by mxmilkiib** [hackmdio/codimd#368]
While I can see benefits for this in some situations, I have the first H1 as the document title so my 'third level' document body is ####, it would be handy if headers of level 4 (and possibly 5) could be displayed via [TOC] or maybe a new tag.

**Comment by a60814billy** [comment]
Thanks @milkmiruku 
Maybe we can add option to TOC tag,
like `[TOC level=4] ` to set TOC level ?

**Comment by ccoenen** [comment]
@milkmiruku if you only need the title for list/overview, you could also add it to the yaml metadata at the top like this

```yaml
---
title: This is my awesome document. There are many like it, but this one is mine!
---
```
see https://hackmd.io/yaml-metadata for more detailed info.

**Comment by milkmiruku** [comment]
@ccoenen thanks, it's more I'd like to use h1 for the document name/title. An alternative idea could be an option to shunt the TOC so it ignores h1 (if there is only one)?

**Comment by jackycute** [comment]
@milkmiruku currently, we don't have an option for customizing TOC ranges.
But maybe this would be nice to have.

**Comment by jackycute** [comment]
I found a good example for the YAML metadata options.

https://shd101wyy.github.io/markdown-preview-enhanced/#/toc?id=toc-and-sidebar-toc-configuration

**Comment by salim-b** [comment]
> I found a good example for the YAML metadata options.
> 
> https://shd101wyy.github.io/markdown-preview-enhanced/#/toc?id=toc-and-sidebar-toc-configuration

An option to set the ToC depth would be really helpful!

Maybe you'd like to just use the same syntax as [R Markdown does](https://bookdown.org/yihui/rmarkdown/html-document.html#table-of-contents)? It looks like this:

```rmd
---
title: "Habits"
output:
  html_document:
    toc: true
    toc_depth: 2
---
```

Then we could set the ToC _separately for each export format_. Of course that would imply some additional implementation work, but since both HackMD/CodiMD _and_ R Markdown/Knitr are relying on Pandoc to convert the Markdown, that would really make sense I guess (the above YAML keys correspond to [Pandoc's CLI options](https://pandoc.org/MANUAL.html#general-writer-options) `--toc` and `--toc-depth`). 🙃

**Comment by jackycute** [comment]
We supported this by https://github.com/hackmdio/codimd/pull/1532
You can use YAML metadata or use `[ToC maxLevel=4]` to specify toc levels.
