### ISSUE TITLE
Versions diff, highlight changes since previous preview

### ISSUE THREAD

**Issue by grmpyninja** [hackmdio/codimd#568]
It'd be awesome to see, some kind of a changelog since the last preview of the note. It'd be really useful to e.g. go to the editor and save the state of it (maybe based on git versioning suggested somewhere) and then when another users does the modifications to see the changes between the last and the current version of the note. Also adding the authors would be simply brilliant, but I guess it might be a bit to much to implement at once (similar to etherpad's highlighting authors).

**Comment by SISheogorath** [comment]
I'm not sure if I got you right, so it would be nice to clear some things up.

Right now we provide the revisions, which are diffs over time.

![Revisions](https://user-images.githubusercontent.com/8719867/31367053-03b9b8ba-ad75-11e7-963f-f15adb0d99c7.png)

If we want to show some kind of diff since the last visit, it would be enough to keep the revision id per user per note and mark the diff in one or another way. 

---

As a second feature, you want the Authors highlighted. Now is the big question: Where? In the editor? Or in the revision view like it was requested in #312? 

If that's really another feature request, we should move it to an own issue, because, otherwise, it becomes more difficult to handle this one.

**Comment by jmuheim** [comment]
While I see a revision, it seems to be empty:

![image](https://user-images.githubusercontent.com/1814983/32658748-c75c976a-c61b-11e7-880b-9e89cf1f4ab9.png)

Is this a bug?

**Comment by ccoenen** [comment]
@jmuheim This is a bug, I would like to ask you to open another ticket, so we can discuss/triage it there.

**Comment by jackycute** [comment]
Hi @jmuheim,

I know this is old, but that is not a bug, the very first revision of your note is empty because we create a baseline version of your note at creation.
BTW, we already support showing diffs in revisions.
