### ISSUE TITLE
Double dollar-sign latex formular breaks editor highlighting

### ISSUE THREAD

**Issue by bengioe** [hackmdio/codimd#625]
Example here: https://hackmd.io/GYJgDA7ARuCMC0BjEBDAzPALAEwKwDZ4BObI4eKWXWNFAUwA5gHMQg==?both#

```markdown
### this header is highlighted in the editor

A $single\; dollar\; formula$

### this header is also highlighted in the editor

$$ double \; \$ dollar\$ \; formula $$

### this header is not highlighted in the editor
```

Happens both in Firefox 57 and Chrome 61.

**Comment by jackycute** [comment]
Hi @bengioe 
For double dollar sign, you have to give new line in before and after to make math block.
For example:
```
$$
double \; \$ dollar\$ \; formula
$$
```

**Comment by SISheogorath** [comment]
Yes, it's an editor or a renderer bug.

@jackycute do you know where in the CodeMirror code the highlighting for MathJax is done? Because it needs to be fixed in one place. For me, it makes sense to fix this in the highlighting code.

**Comment by Stonesjtu** [comment]
There's no highlighting for MathJax in CodeMirror. Instead `sTex` and `LaTeX' are both supported.

I don't know which mode this project is on, but the default `markdown` mode in CodeMirror may not fit our requirements because of the extra mathjax support. Fortunately there's an addon scripts named `multiplex` which may help.
https://github.com/codemirror/CodeMirror/blob/3d89b71b955b72e61430f7f38e2350489cad9e15/addon/mode/multiplex_test.js#L4-L18

refs:
supported modes: https://codemirror.net/mode/index.html
modes for markdown: https://github.com/codemirror/CodeMirror/tree/3d89b71b955b72e61430f7f38e2350489cad9e15/mode/markdown

**Comment by YtvwlD** [comment]
This issue still exists.

Here is a demonstration: https://demo.codimd.org/MHbzXJBXS0WwyjvtY6F-nQ

```markdown
# Full Line Formulae Break Highlighting

<!-- This is a comment. -->

This is a greek letter: $\alpha$.

<!-- another comment -->

$$a^2 + b^2 = c^2$$

<!-- This comment doesn't highlighted. -->
```

**Comment by SISheogorath** [comment]
Well, as mentioned earlier `$$` is for multi-line usage. So the probably bigger problem is that things are rendered correctly on the view side, at least from my perspective.

**Comment by YtvwlD** [comment]
Ah, yes. Thank you.

**Comment by jackycute** [comment]
Please use the following syntax for math and it won't break the highlighting in the editor:

```
$$
double \; \$ dollar\$ \; formula
$$
```
