### ISSUE TITLE
remove all trackers 

### ISSUE THREAD

**Issue by albjeremias** [hackmdio/codimd#864]
I mean google font apis... bootstrap cdn...
don't worry, i'll fork it myself and make a PR soonish!

![image](https://user-images.githubusercontent.com/26681446/41913567-f1952112-7950-11e8-99f4-9c7e1731cbca.png)

![image](https://user-images.githubusercontent.com/26681446/41913617-125607ea-7951-11e8-95a0-ca5be184527d.png)

**Comment by SISheogorath** [comment]
Please check the "usecdn" option on README.md

**Comment by albjeremias** [comment]
then it should be opt-in not opt-out... :|

**Comment by SISheogorath** [comment]
First of all: It's opt out because we don't break existing behaviours. We don't want people to check every config option on an update. So we don't break it and initially HackMD was build using CDNs.

Also about your privacy concerns:
- We include all cdn content with [`crossorigin=anonymous`](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes) set, which means it doesn't send any cookies or similar to the CDN.
- We use [SRI](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) to prevent CDN content to be malicious
- We use [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) to prevent unexpected content to run inside HackMD

So with all this, what does a CDN see from you?
- Your IP-address
- Your request for the resource
- The basic domain name you are requesting it from (e.g. hackmd-ce.herokuapp.com)

So I understand that you are may concerned about privacy, but when you review our protections I hope you'll understand that we call it an acceptable level as it saves a lot of traffic and load on our own servers. Also it really speeds up loading the page since the cdnjs parts are often already cached and stay in cache for a day.

**Comment by albjeremias** [comment]
ill make a PR specifying documentation for docker!
