### ISSUE TITLE
Mattermost authentication doesn't work with Mattermost v5.0 and up

### ISSUE THREAD

**Issue by maxer456** [hackmdio/codimd#916]
Hello,

Right now, Mattermost authentication is broken for Mattermost versions 5.0 and higher, trying to log in results in an "Internal Server Error" page.

The library CodiMD uses for interaction with the Mattermost API uses the older v3 API, which has been deprecated and removed. The library is no longer maintained and their [readme](https://github.com/mattermost/mattermost-driver-javascript) recommends using the v4 API driver from the [mattermost-redux](https://github.com/mattermost/mattermost-redux) repository.

Mattermost's [OAuth2 client sample](https://github.com/mattermost/mattermost-oauth2-client-sample) already uses the v4 API driver.

It would be awesome if this got fixed, if possible.

**Comment by SISheogorath** [comment]
Can you try to use the [generic oauth module](https://github.com/hackmdio/codimd/pull/784/files#diff-b244c067c02a98d0b69bc198233055fd) (which I just realized is not documented). And if it works, would you like to contribute a guide ([like for GitHub](https://github.com/hackmdio/codimd/blob/master/docs/guides/auth/github.md)) on how to set it up?

Since I already noticed that the mattermost integration is outdated and I want to replace it in future with a guide instead.

**Comment by maxer456** [comment]
Okay, I managed to get the generic OAuth module working with Mattermost. I have a questions though. Is the baseURL setting actually used somewhere? For authentication, I have to specify the full URL in every setting anyway.

I'll be happy to make a guide on how to set this up once I'm sure I have set it up correctly.

**Comment by SISheogorath** [comment]
Fixed by #929
