### ISSUE TITLE
Custom theme/css

### ISSUE THREAD

**Issue by unteem** [hackmdio/codimd#946]
Hi. 
Is there a way to customize a codimd instance? 
Change the picture, colors etc.
thx

**Comment by SISheogorath** [comment]
We currently don't support something like this, without forking CodiMD.

I'm also not sure if we really want to support this, because what I mainly see is upcoming issues that are now related to customized CSS feature that then may break the editor or rendered output. I would really like to avoid that.

On the other hand I understand when people want to have their logo somewhere. Let's see what the community says :)

**Comment by ccoenen** [comment]
I think it's sensible to have some simple customisation leeway.

If there were something like an optional `CMD_ADDITIONAL_CSS=bernd.css`, that would take one CSS filename, that's loaded LAST, this would enable simple customisations like logo swapping without much hassle. One COULD totally go nuts with this and overwrite EVERYTHING, but I doubt that this would actually happen in the wild.

Maybe it's even easier to just package this automatically by webpack, but I don't know much about the current packaging process.

**Comment by unteem** [comment]
@SISheogorath base case, as @ccoenen said, would only be to choose the color scheme and put a logo somewhere. Nothing crazy, most open source apps offer this kind of customization.
In my case a codimd instance often comes with a rocket.chat and nextcloud instance, if the design doesn't match, it makes it confusing. 
I can try to help, I'll need some guidance though

**Comment by SISheogorath** [comment]
To be honest I would still like to avoid that. Not because I think we are the best UI or UX designers out there. But because it's just one more place to break things.
Friend of mine pointed that out in an own blog post a while ago: https://blog.no42.org/article/theming-applications/

**Comment by unteem** [comment]
OK. I would say maybe it is still something to consider in the future.

I kind of disagree with the blog post though. If the main issue is that users will make a bad ui/ux, well too bad for them :). If it makes them happy to have their logo and color scheme, let it be.

If the main issue is that it can lead to difficulties maintaining codimd and that is something the main contributors don't want to do, that id another debate :)

**Comment by SISheogorath** [comment]
If you like, we can discuss it more detailed during the [upcoming community call](https://github.com/hackmdio/codimd/issues/911) on Sunday.

But yes, my main issue is that people may break UI/UX. And broken UI/UX leads to unneeded issues over here. It needs to be addressed and basically has the answer: "yeah, that's how it is, talk to your admin to unbreak it".

Also configuring it is not trivial. Do we want to add it as additional request? Not so much, this slows down loading, so we want to process it with Webpack. That again makes it unusable with all prebuilt images. So it's only for native setups.

Instead I would prefer it when people who want their own branding simply fork CodiMD and maintain this fork (which includes to link to their own source code instead of us). This helps us to innovate (because some UI/UX changes are maybe quite cool and should be shared with the community) and allows them to keep their changes compatible with newer CodiMD releases.

**Comment by ccoenen** [comment]
> ability to customize the look and feel just a bit by allowing users to replace the icon.
(@gkoerk in #1032)

**Comment by gkoerk** [comment]
Was anything decided at the community call on this topic?

**Comment by SISheogorath** [comment]
There was no talking about this topic during the community talk last week. The topic didn't came up.

If you like to join we can talk about it this Sunday, which is the next community call.

*Notice*: We don't make any final decisions in the call, since we are distributed across the entire planet, we don't want to make final decisions in an synchronous event. So when there is any final decision on this, It'll be done in here.

**Comment by jackycute** [comment]
You are welcomed to customize CodiMD theme, colors, branding anytime by forking this repo and make modifications.
