### ISSUE TITLE
Create development branch

### ISSUE THREAD

**Issue by mcueto** [hackmdio/codimd#948]
I know that is hard to get the people working on an open source project and keep it all clean and organized, so i propose:
- Create a development branch to keep the new features separated from master
- Update master ONLY with stable changes every release(keeping the tags version system tho)

**Comment by SISheogorath** [comment]
I already considered this earlier, but throw the idea away since this project is not big enough to have any real benefit from it.

Let's say we create a development branch and run development there. This would also become our new main branch and the branch we use for automatic deployment.

The master branch itself boils down to a list of tags. With the latest tag on top.

Everything else would stay as it is.

So while it makes sense to simplify deployments in business by using this "latest tag on top" approach, I don't see how it makes sense for us.

We want people to use the pre-build versions and those who don't use them, can checkout the tags themselves, easily or just use the output from the GitHub release page.

And yes, I'm aware of the ["successful git branching model"](https://nvie.com/posts/a-successful-git-branching-model/) as well as "a successful git branching model co[nsidered harmful"](https://barro.github.io/2016/02/a-succesful-git-branching-model-considered-harmful/) and some other guides through git. There are tons of different branching models out there and I think we already "cherry-picked" :wink:  various good features that work for us.

I also don't see where our development is under the pressure of improving the branching model. But may you can provide an example or details why you think we need a development branch?

The only possible need I see near future is **maybe** the use of release branches.

**Comment by SISheogorath** [comment]
Since there was no further this discussion I think we'll stay with the current model. Thanks for your ideas!
